### ISSUE TITLE
About Multiplayer Support

### ISSUE THREAD

**Issue by microaijp** [DAN-AND-DNA/UE4_EasyMobileInput#1]
![screenshot](https://user-images.githubusercontent.com/4074813/174729004-08a5e024-6bc2-4ab3-86c9-42f6ad55c4c1.png)

After setting up a 2-player multiplayer setup, when I move the joystick, the same character moves.

Is there any way to make it multiplayer compatible?

**Comment by DAN-AND-DNA** [comment]
Hi @goroakimoto , this simple demo does not support multiplayer, it is only used to illustrate how to use the plugin

**Comment by microaijp** [comment]
Thanks for the reply. I will try to do it myself somehow.

**Comment by DAN-AND-DNA** [comment]
@goroakimoto try mobile preview:
![image](https://user-images.githubusercontent.com/28588158/174748190-8915dfe1-cb81-4589-b0f6-5627338dd252.png)
![image](https://user-images.githubusercontent.com/28588158/174748059-af249fed-6a07-4937-937b-ed48eeff9852.png)

**Comment by DAN-AND-DNA** [comment]
Create the UMG as follows to avoid errors:
![image](https://user-images.githubusercontent.com/28588158/174748672-93af2dc4-6a57-4ffb-a103-da8eea176724.png)

**Comment by DAN-AND-DNA** [comment]
@goroakimoto  If you have any other questions, please feel free to ask me!

**Comment by microaijp** [comment]
I just ran it through mobile preview and it worked separately! Thank you so much!
